[toolchain]

[features]
seeds = true
skip-lint = false

[programs.devnet]
beeproof = "8eLXGBggKm9Svwpq1UXUbrZeFTvEEosfwkXYcSP7WxeY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "../backend/src/config/solana-wallet.json"

[scripts]
test = "node ../backend/test/backend-test.js"
